---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: R1-Exam
  gather_facts: false
  connection: network_cli
 
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     cisco.ios.ios_command:
       commands:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT
     ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "show_run_66070221_R1-Exam.txt"
